# Generated by Django 5.1.6 on 2025-03-21 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'กำลังจอง'), ('booked', 'จองแล้ว'), ('cancelled', 'ยกเลิก')], default='pending', max_length=20),
        ),
    ]
